# Generated by Django 4.1.1 on 2022-12-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.CharField(max_length=255),
        ),
    ]
